name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: infinitecrew
          POSTGRES_PASSWORD: infinitecrew
          POSTGRES_DB: infinitecrew
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Initialize database
      env:
        DATABASE_URL: postgresql://infinitecrew:infinitecrew@localhost:5432/infinitecrew
      run: |
        PGPASSWORD=infinitecrew psql -h localhost -U infinitecrew -d infinitecrew -f scripts/init.sql
    
    - name: Run tests
      env:
        REDIS_URL: redis://localhost:6379
        DATABASE_URL: postgresql://infinitecrew:infinitecrew@localhost:5432/infinitecrew
        OPENAI_API_BASE: https://api.together.xyz/v1
        OPENAI_API_KEY: test_key
        CREWAI_MODEL_NAME: mistralai/Mixtral-8x7B-Instruct-v0.1
      run: |
        python tests/test_connections.py
        python tests/test_decomposition.py